# Introduction to Twitter dataset

In [1]:
import pandas as pd
tweets = pd.read_excel('../data/stockerbot-export.xls')
tweets

,id,text,timestamp,source,symbols,company_names,url,verified,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,1019696670777500032,VIDEO: â€œI was in my office. I was minding my...,Wed Jul 18 21:33:26 +0000 2018,GoldmanSachs,GS,The Goldman Sachs,https://twitter.com/i/web/status/1019696670777...,True,NaN,NaN,NaN,NaN
1,1019709091038540032,The price of lumber $LB_F is down 22% since hi...,Wed Jul 18 22:22:47 +0000 2018,StockTwits,M,Macy's,https://twitter.com/i/web/status/1019709091038...,True,NaN,NaN,NaN,NaN
2,1019711413798029952,Who says the American Dream is dead? https://t...,Wed Jul 18 22:32:01 +0000 2018,TheStreet,AIG,American,https://buff.ly/2L3kmc4,True,NaN,NaN,NaN,NaN
3,1019716662587740032,Barry Silbert is extremely optimistic on bitco...,Wed Jul 18 22:52:52 +0000 2018,MarketWatch,BTC,Bitcoin,https://twitter.com/i/web/status/1019716662587...,True,NaN,NaN,NaN,NaN
4,1019718460287379968,How satellites avoid attacks and space junk wh...,Wed Jul 18 23:00:01 +0000 2018,Forbes,ORCL,Oracle,http://on.forbes.com/6013DqDDU,True,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
28434,1019730088617629952,$FB : 29234a9c-7f08-4d5a-985f-cb1a5554ecf9,Wed Jul 18 23:46:13 +0000 2018,test5f1798,FB,Facebook,NaN,False,NaN,NaN,NaN,NaN
28435,1019730115524280064,ã€ä»®æƒ³é€šè²¨ã€‘ãƒ“ãƒƒãƒˆã‚³ã‚¤ãƒ³ã®ä¾¡æ ¼ä...,Wed Jul 18 23:46:19 +0000 2018,keizai_toushi17,BTC,Bitcoin,http://keizai-toushi-navi.com/?p=26838,False,NaN,NaN,NaN,NaN
28436,1019730115805180032,RT @invest_in_hd: 'Nuff said! $TEL #telcoin #...,Wed Jul 18 23:46:19 +0000 2018,iad81,BTC,Bitcoin,https://twitter.com/CRYPTOVERLOAD/status/10178...,False,NaN,NaN,NaN,NaN
28437,1019730117252339968,ã€ä»®æƒ³é€šè²¨ã€‘ãƒ“ãƒƒãƒˆã‚³ã‚¤ãƒ³ã®ä¾¡æ ¼ä...,Wed Jul 18 23:46:20 +0000 2018,O8viWMyrCV6cBOZ,BTC,Bitcoin,http://true.velvet.jp/monexx/archives/2357,False,NaN,NaN,NaN,NaN
28438,1019730146180409984,Stellar $XLM price: $0.297852 Binance registra...,Wed Jul 18 23:46:27 +0000 2018,Descendent92,AMP,Ameriprise Financial,https://twitter.com/i/web/status/1019730146180...,False,NaN,NaN,NaN,NaN

In [2]:
# Find out the most common tickers
value_counts = tweets['symbols'].value_counts()
value_counts

NFLX        101
HON         100
MOMO        100
ES          100
GPS         100
           ...
TWTR          1
INTC-USB      1
GS            1
AMZN-GPS      1
ORCL          1
Name: symbols, Length: 453, dtype: int64

In [3]:
# Example tweet
tweets['text'].iloc[0]

'VIDEO: â€œI was in my office. I was minding my own business...â€\x9d â€“David Solomon tells $GS interns how he learned he waâ€¦ https://t.co/QClAITywXV'

In [9]:
# What are Facebooks tweets
tweets[tweets['symbols']=='FB']['text'].iloc[0]

'New time: Janet Yellen and I in conversation at Brookings on Feb. 27 at 2 PM EST. Join us online or on Facebook Livâ€¦ https://t.co/hDg7X5Rc5P'

In [10]:
# ... not relevant. Oracle seems to have a paid tweet 
tweets[tweets['symbols']=='ORCL']['text'].iloc[0]

'How satellites avoid attacks and space junk while circling the Earth https://t.co/aHzIV3Lqp5 #paid @Oracle https://t.co/kacpqZWiDJ'

In [12]:
# There are also combination tickers in the dataset but only three so not too relevant
i = value_counts.index.str.contains('-')
value_counts.loc[i]

FB-GOOGL-GOOG    1
INTC-USB         1
AMZN-GPS         1
Name: symbols, dtype: int64

In [15]:
# Doing some regular expressions 
import re
value_counts.index.loc['AMZN']

AttributeError: 'Index' object has no attribute 'loc'

In [19]:
i = value_counts.index.str.contains('NFLX')
value_counts.loc[i]

NFLX    101
Name: symbols, dtype: int64

In [21]:
# NFLX occurs 101 times, let's see if it mentioned in any other tweets.
# Lets investigate what other stocks were mentioned when NFLX was the symbol being discussed

for tweet in tweets[tweets['symbols']=='NFLX']['text']:
    print(re.findall('\$[a-zA-Z]+', tweet))

[]
['$NFLX']
[]
['$FANG', '$FB', '$AMZN']
['$SPY', '$NFLX', '$UVXY', '$MS', '$CSX', '$ABT', '$UAL']
['$HMNY', '$AMD', '$MU']
['$NFLX']
['$CL']
['$FANG', '$FB', '$AMZN']
['$TWTR', '$FB', '$AAPL', '$NFLX', '$TSLA', '$AMZN', '$GOOGL']
['$TSLA']
['$NFLX', '$BAC', '$FB', '$MSFT', '$AAPL', '$MSFT', '$TWTR', '$BABA', '$TWTR', '$JD', '$NXPI', '$AMD', '$JPM', '$MU', '$TSLA', '$MS', '$C', '$ROKU', '$CSX']
['$FANG', '$FB', '$AMZN']
['$ABMD', '$CRM', '$PANW', '$TWTR', '$ALGN', '$NOW', '$FB', '$NFLX', '$ILMN', '$MA', '$V', '$LULU', '$ADBE', '$GOOGL', '$ISRG', '$A']
['$NFLX']
['$MS', '$BAC', '$CPAH']
['$NFLX', '$SIRI', '$SPOT', '$T', '$AMZN', '$DIS']
['$NFLX', '$SIRI', '$SPOT', '$T', '$AMZN', '$DIS']
[]
['$NFLX', '$SIRI', '$SPOT', '$T', '$AMZN', '$DIS']
['$TSLA', '$NFLX', '$BIDU', '$BABA', '$GOOGL', '$DIS']
['$SPY', '$NFLX', '$UVXY', '$MS', '$CSX', '$ABT', '$UAL']
['$NFLX']
['$AAPL', '$AMZN', '$NFLX', '$GOOGL', '$SPX', '$TWTR']
['$SPOT', '$NFLX', '$SIRI']
['$NFLX', '$SIRI', '$SPOT', '$T', '$AMZN', '$DIS']
['$SPX', '$NFLX']
['$NFLX']
['$FANG', '$FB', '$AMZN']
['$NFLX', '$BAC', '$FB', '$MSFT', '$AAPL', '$MSFT', '$TWTR', '$BABA', '$TWTR', '$JD', '$NXPI', '$AMD', '$JPM', '$MU', '$TSLA', '$MS', '$C', '$ROKU', '$CSX']
['$NFLX']
['$NFLX']
['$DJIA', '$QQQ', '$NFLX', '$FB']
['$TWTR', '$AMZN', '$NFLX', '$GOOGL', '$BABA', '$C', '$FB']
['$SPX', '$NFLX']
['$NFLX', '$SIRI']
['$NFLX']
['$NFLX']
['$TSLA']
['$NFLX']
['$SPX']
['$NFLX', '$ROKU']
['$DJIA', '$QQQ', '$NFLX', '$FB']
['$NFLX', '$MS']
['$BABA', '$NVDA', '$AMZN', '$NFLX', '$GOOGL']
['$IBM', '$NFLX']
['$FB', '$NFLX', '$AMZN', '$SPX', '$TSLA', '$AAPL', '$GS']
['$ebay']
['$NFLX', '$BAC', '$MU', '$FB', '$AAPL', '$MSFT', '$BABA', '$F', '$JD', '$GE', '$IBM', '$TWTR', '$GGP', '$AAL', '$TSLA', '$NXPI', '$AMD', '$SBUX', '$PG', '$EBAY', '$JPM', '$MS', '$UAL']
['$NFLX']
['$AMZN']
['$UAL', '$CSX', '$DAL', '$AAL', '$FOXA', '$EBAY', '$AMZN', '$WMT', '$SBUX', '$CMCSA', '$BABA', '$NFLX']
['$FANG', '$FB', '$AMZN']
['$NFLX']
[]
['$SBUX', '$NFLX']
[]
[]
[]
[]
['$SPX']
['$NFLX', '$TSLA', '$AAPL', '$IBB', '$GS', '$FB', '$AMZN', '$GOOGL', '$NVDA']
['$JD', '$GE', '$BAC', '$F', '$FB', '$NFLX', '$AABA', '$MU', '$AAPL', '$CMCSA', '$PG', '$AAL', '$WFC', '$SBUX', '$FOXA']
['$DJIA', '$QQQ', '$NFLX', '$FB']
['$FANG', '$FB', '$AMZN']
[]
['$AMZN', '$IBB', '$XLY', '$XLK', '$FB', '$AMZN', '$MSFT', '$AAPL', '$GOOGL']
['$AAPL', '$AMZN', '$NFLX', '$GOOGL', '$SPX', '$TWTR']
['$IQ', '$NFLX']
['$TWTR', '$RH', '$AAPL', '$NFLX', '$TSLA', '$AMZN', '$GOOGL']
['$NFLX']
['$NFLX', '$EROS', '$IFN', '$EPI']
['$SPY', '$NFLX', '$UVXY', '$MS', '$CSX', '$ABT', '$UAL']
['$NFLX']
['$WMT', '$AMZN', '$NFLX', '$WMT']
[]
['$NFLX']
['$nflx', '$amzn', '$aapl', '$goog', '$nwl', '$nvda', '$ibm']
['$NFLX', '$BABA', '$UAL', '$AAPL', '$BAC', '$F', '$TWTR', '$JPM', '$MS', '$NXPI', '$MU', '$AAL', '$MSFT', '$GGP', '$TSLA', '$SBUX', '$IBM', '$EBAY', '$PG', '$AMD', '$JD', '$FB', '$GE']
['$FANG', '$FB', '$AMZN']
['$NFLX']
['$nflx']
['$NFLX']
['$NFLX']
['$AAPL', '$AMZN', '$NFLX', '$GOOGL', '$SPX', '$TWTR']
[]
['$FANG', '$FB', '$AMZN']
['$NFLX', '$AMZN', '$ADDYY', '$AAPL', '$DIS']
['$FANG', '$FB', '$AMZN']
['$TWTR', '$AMZN', '$NFLX', '$GOOGL', '$WIX', '$GS', '$FB']
[]
['$FB', '$TWTR', '$NFLX']
['$TSLA', '$NFLX']
[]
['$NFLX']
['$AAPL', '$AMZN', '$NFLX', '$GOOGL', '$SPX', '$TWTR']
['$NFLX']
['$TSLA', '$NFLX']
['$NFLX', '$AMZN', '$ADDYY', '$AAPL', '$DIS']
['$AMZN', '$GOOGL', '$NFLX', '$BA', '$TSLA', '$TWTR', '$SQ', '$ROKU']
['$SQ', '$NFLX', '$AMZN', '$AMD', '$TSLA', '$AAPL', '$GS']

In [24]:
# Applying this to the dataframe
tweets_df = tweets[tweets['symbols']=='NFLX']['text'].apply(lambda tweet: re.findall('\$[a-zA-Z]+', tweet))
tweets_df

8                                                       []
26391                                              [$NFLX]
26398                                                   []
26411                                  [$FANG, $FB, $AMZN]
26414          [$SPY, $NFLX, $UVXY, $MS, $CSX, $ABT, $UAL]
                               ...
28201                                              [$NFLX]
28241                                       [$TSLA, $NFLX]
28274                  [$NFLX, $AMZN, $ADDYY, $AAPL, $DIS]
28290    [$AMZN, $GOOGL, $NFLX, $BA, $TSLA, $TWTR, $SQ,...
28412         [$SQ, $NFLX, $AMZN, $AMD, $TSLA, $AAPL, $GS]
Name: text, Length: 101, dtype: object

In [27]:
# Then convert it to a boolean index signifying connections by mapping arrays to series
matrix = tweets_df.apply(lambda contained: pd.Series(1, index=set(map(str.upper, contained)))).fillna(0)
matrix

,$NFLX,$FANG,$AMZN,$FB,$ABT,$CSX,$UVXY,$SPY,$MS,$UAL,...,$RH,$EPI,$IFN,$EROS,$GOOG,$NWL,$ADDYY,$WIX,$BA,$SQ
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26391,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26411,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26414,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28201,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28241,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28274,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
28290,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
28412,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [30]:
# Most commonly cross referenced for Netflix
cross_reference = matrix.sum()
cross_reference

$NFLX     69.0
$FANG      9.0
$AMZN     33.0
$FB       25.0
$ABT       3.0
          ...
$NWL       1.0
$ADDYY     2.0
$WIX       1.0
$BA        1.0
$SQ        2.0
Length: 77, dtype: float64

In [ ]:
# Turning this process into a function
def outward_connections(tweets):
    return tweets_df.apply(lambda contained: pd.Series(1, index=set(map(str.upper, contained)))).fillna(0)